# Use the official ArangoDB image as the base image
FROM arangodb:3.12

# Install curl using apk
RUN apk update && \
    apk add --no-cache curl

# Set the entrypoint and command to start ArangoDB with RocksDB storage engine
ENTRYPOINT ["/entrypoint.sh"]
CMD ["--server.storage-engine=rocksdb"]