# Use the official ArangoDB image as the base image
FROM arangodb:3.12

# Install curl and bash using apk
RUN apk update && \
    apk add --no-cache curl bash

# Set the entrypoint and command to start ArangoDB with RocksDB storage engine
ENTRYPOINT ["/entrypoint.sh"]
CMD ["--server.storage-engine=rocksdb"]
