version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: hades_test
      POSTGRES_PASSWORD: hades_test
      POSTGRES_DB: hades_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hades_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: password
    ports:
      - "8530:8529"
    volumes:
      - arango_test_data:/var/lib/arangodb3
    command: arangod --server.endpoint tcp://0.0.0.0:8529
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_api/version", "-u", "root:password"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
  arango_test_data:
