version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=0  # Authentication enabled
      - ARANGO_ROOT_PASSWORD=  # Empty root password for initial setup
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
      - arango_apps:/var/lib/arangodb3-apps

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=hades
      - POSTGRES_PASSWORD=o$n^3W%QD0HGWxH!
      - POSTGRES_DB=hades_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  arango_data:
  arango_apps:
  postgres_data:
