"""
ArangoDB test environment variables.
This file is auto-generated by setup_arango_test_db.py.
"""
# ArangoDB connection parameters for tests
ARANGO_TEST_PARAMS = {
    "host": "http://localhost:8529",
    "username": "hades",
    "password": "dpvL#tocbHQeKBd4",
    "database": "hades_graph"
}
