# PostgreSQL test environment parameters
# This file is auto-generated by setup_test_databases.py
# Do not edit manually

PG_TEST_PARAMS = {
    "dbname": "hades_test",
    "user": "hades",
    "password": "o$n^3W%QD0HGWxH!",
    "host": "localhost",
    "port": "5432"
}
